/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample_1;

import sample_1.App;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.TestInstance;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class AppTest {

    App mApp;

    @BeforeAll
    public void Setup()
    {
       mApp = new App( 0 ); 
    }

    @Test
    public void multiplicationOfZeroIntegereShouldReturnZero() {
        App vApp = new App(); //can be heavyweight!

        assertEquals(0, vApp.multiply(10, 0), "10 x 0 must be 0");
        assertEquals(0, vApp.multiply(0, 10), "0 x 10 must be 0" );
        assertEquals(0, vApp.multiply(0, 0), "0 x 0 must be 0");
    }

    @Test
    public void multiplicationOfZeroIntegereShouldReturnZeroWithMember() {
        assertEquals( 0, mApp.multiply(10, 0), "10 x 0 must be 0");
        assertEquals( 0, mApp.multiply(0, 10), "0 x 10 must be 0");
        assertEquals( 0, mApp.multiply(0, 0), "0 x 0 must be 0");
    }

    @Test
    public void beforeAffectsTest(){
        assertFalse( false );
    }

    @AfterAll
    public void TearDown()
    {
        assert( true );
    }
}
