/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import org.example.values.CannedWalrusFood;
import org.example.values.Walrus;
import org.example.values.WalrusFood;

public class WalrusTest {
    private Walrus marco;
    private WalrusFood food1;
    private CannedWalrusFood can;

    @Before
    public void setup() {
        marco = new Walrus();
        food1 = new WalrusFood();
        can = new CannedWalrusFood(food1);
    }

    @Test
    public void testhowmuchawalruscaneat() {
        int foodamount = 1000; //it can be changed to a much larger number
        int eatenfoodcounter = 0;
    
        for (int i = 0; i < foodamount; i++) {

            marco.addToStomach(food1);

            if (marco.hasEaten(food1)) {
                eatenfoodcounter++;
            }
        }
    
        assertEquals(foodamount, eatenfoodcounter);
    }
    
    
    @Test
    public void testwalrusgetstherightfood() {
        WalrusFood food2 = new WalrusFood();

        marco.addToStomach(food1);
        marco.addToStomach(food2);

        assertTrue(marco.hasEaten(food1));
        assertTrue(marco.hasEaten(food2));
    }
    
    @Test
    public void testopeningacan() {
        OpensCan opens = new OpensCan();
        WalrusFood result = opens.open(can);

        assertEquals(food1, result);
    }
    
    @Test //test case 1 for task 4
    public void testhowawalruscaneat1(){
        FeedsWalrus feeds = new FeedsWalrus();

        feeds.feed(marco, can);

        assertTrue(marco.hasEaten(food1));
    }

    @Test //test case 2 for task 4
    public void testhowawalruscaneat2(){
        marco.addToStomach(food1);

        assertTrue(marco.hasEaten(food1));
    }
    
    @Test //test case 1 for task 5
    public void testwalrusacceptnonvalrusfood1(){
        marco.addToStomach(null);
        
        assertFalse(marco.hasEaten(null));
    }


    public class NonWalrusFood extends WalrusFood {}

    @Test //test case 2 for task 5
    public void testwalrusacceptnonvalrusfood2() {
        WalrusFood notrealfood = new NonWalrusFood();

        marco.addToStomach(notrealfood);

        assertTrue(marco.hasEaten(notrealfood)); 
    }
}
