/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.values;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class WalrusTest {

    private Walrus walrus;
    private WalrusFood food1;
    private WalrusFood food2;

    @BeforeEach
    void setUp() {
        walrus = new Walrus();
        food1 = new WalrusFood();
        food2 = new WalrusFood();
    }

    @Test
    void testWalrusCanEatMultipleFood() {
        walrus.addToStomach(food1);
        walrus.addToStomach(food2);
        assertTrue(walrus.hasEaten(food1));
        assertTrue(walrus.hasEaten(food2));
    }

    @Test
    void testWalrusCanRecognizeEatenFood() {
        walrus.addToStomach(food1);
        assertTrue(walrus.hasEaten(food1));
        assertFalse(walrus.hasEaten(new WalrusFood()));
    }

    @Test
    void testWalrusEatingCausesStateChange() {
        assertFalse(walrus.hasEaten(food1));
        walrus.addToStomach(food1);
        assertTrue(walrus.hasEaten(food1));
    }

    @Test
    void testRejectInvalidFood() {
        walrus.addToStomach(null); // 不应报错
        assertFalse(walrus.hasEaten(new WalrusFood())); // null 不应算吃了
    }
}


